import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import ItemDisplay from '../components/ItemDisplay'

export default function Home({ products }) {
	return (
		<div>
			<Head>
				<title>This Store: It's amazing!</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			<main>
				<ItemDisplay products={products} />
			</main>

			<footer>
				<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
			</footer>
		</div>
	)
}

export async function getStaticProps() {
	// This function will get the data that will be displayed and arranged
	const res = await fetch('https://fakestoreapi.com/products')
	const products = await res.json()

	return {
		props: {
			products,
		},
	}
}
