import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import ItemDisplay from '../components/ItemDisplay'

export default function Home({ products }) {
	return (
		<>
			<Head>
				<title>This Store: It's amazing!</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			<header>
				<nav>
					{/* Logo Here */}

					{/* Use Link attribute to move to new page */}
					<a>Men</a>
					<a>Women</a>
					<a>Jewelry</a>
					<a>Electronics</a>
				</nav>
			</header>

			<header className={styles.wallHeader}>
				<h1>Stuff We Have ({products.length})</h1>
				{/* SideNav toggle & Sort By */}
				<nav className={styles.sortNav}>
					{/* Toggle sideNav Button */}
					<button>Hide Filters</button>
					{/* Sort By Button */}
					<button>Sort By</button>
				</nav>
			</header>

			<div className={styles.bodyContainer}>
				{/* Side Nav for filtering results */}
				<nav className={styles.sideNav}>
					<fieldset>
						<legend>Price ($)</legend>
						<div>
							<input type="radio" id="anyPrice" name="price" defaultChecked></input>
							<label for="anyPrice">Any price</label>
						</div>
						<div>
							<input type="radio" id="underTen" name="price"></input>
							<label for="underTen">Under $10</label>
						</div>
						<div>
							<input type="radio" id="tenToTwentyFive" name="price"></input>
							<label for="tenToTwentyFive">$10 to $25</label>
						</div>
						<div>
							<input type="radio" id="twentyFiveToOneHundred" name="price"></input>
							<label for="twentyFiveToOneHundred">$25 to $100</label>
						</div>
						<div>
							<input type="radio" id="oneHundredToFiveHundred" name="price"></input>
							<label for="oneHundredToFiveHundred">$100 to $500</label>
						</div>
						<div>
							<input type="radio" id="overFiveHundred" name="price"></input>
							<label for="overFiveHundred">Over $500</label>
						</div>
						<div>
							<input type="radio" id="customRadio" name="price"></input>
							<label for="customRadio">Custom</label>
							<div>
								<input type="text" maxlength="5" placeholder="Low"></input>
								<p>to</p>
								<input type="text" maxlength="5" placeholder="High"></input>
							</div>
						</div>
					</fieldset>
				</nav>

				<main className={styles.main}>
					<ItemDisplay products={products} />
				</main>
			</div>

			<footer>
				<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
			</footer>
		</>
	)
}

export async function getStaticProps() {
	// This function will get the data that will be displayed and arranged
	const response = await fetch('https://fakestoreapi.com/products')
	const products = await response.json()
	// If there is an error with the api call then a custom 500 error page will display.
	return {
		props: {
			products,
		},
	}
}
